<a href="https://colab.research.google.com/github/litlsun/hse_programming/blob/main/Second_workbook_types_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(c) В.И. Фирсанова | 2024

# Типы данных в Python

1. **Числовые типы**:
   - `int` integer, целое число `7`
   - `float` число с плавающей точкой (десятичная дробь) `7.1`

2. **Булевы перменные**:
   - `Bool` Boolean, принимает значения `True` или `False`

3. **Наборы, последовательности**:
   - `str` string, строка `"hello"`
   - `list`, список `[1, 7.1, "hello"]`, изменяемая последовательность
    - *вложенный список* состоит из множества списков `[[0, 1, 2], [3, 4]]`
   - `tuple`, кортеж `(1, 7.1, "hello), неизменяемая последовательность
    - в кортежах нельзя удалять, добавлять данные; они занимают меньше памяти
   - `dict`, dictionary, словарь `{"number": 1, "word": "hello"}`, пары ключей и значений (key-query)
    - в этом примере ключами будут `"number"` и `"word"`, а значениями - `1` и `"hello"`
  - `set`, множество, неупорядоченный набор уникальных элементов `{1, 2, 3}`
  - `frozenset`, неизменяемое множество (аналог кортежа по отношению к спискам)

4. **None**:
   - `None` можно использовать для создания пустого элемента, как плейсхолдер в функции, для проверки факта наличия объекта в переменной и т.д.

Задачи

1. Угадай число

In [2]:
import random # библиотека для генерации случайных чисел

# генерируем случайное целое число (random integer) от 0 до 10
# функция randint принимает два аргумента: диапазон генерации
magic_number = random.randint(0, 10)

# запросите у пользователя ввод числа
user_number = int(input('Введите число от 0 до 10: '))

if user_number == magic_number: # проверка на совпадение значений
  print('Поздравляю, вы угадали!')
else:
  print('А вот и нет! Это число', magic_number)

Введите число от 0 до 10: 8
А вот и нет! Это число 4

Обратите внимание на строку `print('А вот и нет! Это число', magic_number)`

`print` может принимать несколько аргументов через запятую и выводить на экран их все!

Используйте это в следующем задании.

2. Приветствие

In [7]:
# запросите у пользователя его имя
# вспомните, чем input(int()) отличается от input()
user_name = input()

# выведите на экран любое приветствие для пользователя
print('Привет,', user_name, '!')

Катя
Привет, Катя !

3. Конвертер температур

In [25]:
# запросите у пользователя температуру в градусах Цельсия:
# это должно быть дробное числом (float)
celcius = float(input('Введите температуру в градусах Цельсия: '))

# конвертируйте температуру из градусов Цельсия в градусы Фаренгейта:
# вспомните или найдите формулу и используйте арифметические операции python для расчетов
farenheit = celcius * 1.8 + 32

# выведите результат на экран:
# используйте любые текстовые формулировки, чтобы показать число,
# которое вы получили от пользователя, и результат расчетов
print(f'Температура в градусах Цельсия: {celcius}\nТемпература в градусах Фаренгейта: {farenheit}')

Введите температуру в градусах Цельсия: 232.778
Температура в градусах Цельсия: 232.778
Температура в градусах Фаренгейта: 451.0004

Как вывести на экран несколько строк?

- Можно вызвать `print` несколько раз

```
print('Вот первая строка')
print('А это вторая строка')
```
- Можно использовать `\n` - символ новой строки

```
print('Вот первая строка \n А это вторая строка')
```

4. Округление и вывод с помощью новой строки

In [26]:
# результат расчетов в задаче 3 сохранился в переменных
# воспользуемся этим преимуществом!

# округлите оба значения температур в градусах Цельсия и в градусах Фаргентейта
# вы можете преобразовать результат к виду целого числа с помощью int(n); n - число для преобразования
# либо воспользоваться функцией round(n, k), указав в аргументах функции количество знаков после запятой k
# попробуйте оба варианта!
celcius = round(celcius, 2)
farenheit = round(farenheit, 1)

# теперь выведите на экран оба числа
# сделайте это в одну строчку кода:
# используйте символ новой строки, подумайте, куда его добавить
print(f'Температура в градусах Цельсия: {celcius}\nТемпература в градусах Фаренгейта: {farenheit}')

Температура в градусах Цельсия: 232.78
Температура в градусах Фаренгейта: 451.0

In [27]:
print(f'Температура в градусах Цельсия: {int(celcius)}\nТемпература в градусах Фаренгейта: {int(farenheit)}')

Температура в градусах Цельсия: 232
Температура в градусах Фаренгейта: 451

В задании 4 нам может помочь свойство конкатенации строк.

`print('Hello' + ' ' +'World')`

Но сложение строки с числом невозможно в питоне. Что делать?

5. Конвертирование типов данных

In [36]:
# преобразуйте округленные значения температур к виду строк, применив str(n),
# где n - то, что вы хотите преобразовать к виду строки
celcius = str(celcius)
farenheit = str(farenheit)

# выведите на экран результат:
# используйте конкатенацию строк вместо запятой в функции print
print('Температура в градусах Цельсия: ' + celcius + ', \nТемпература в градусах Фаренгейта: ' + farenheit)

Температура в градусах Цельсия: 232.78,
Температура в градусах Фаренгейта: 451.0

Чтобы преобразовать один тип данных в другой, мы вызываем функцию, обозначающую этот тип.

Закрепим новый материал.

6. Калькулятор

In [38]:
# запросите у пользователя 2 целых числа
# выполните операции сложения, вычитания, умножения и возведения каждого из чисел во вторую степень
# выведите результат на экран

first_number = int(input('Введите первое число: '))
second_number = int(input('Введите второе число: '))
print(f'Результат сложения: {first_number + second_number}\nРезультат вычитания: {first_number - second_number}\nРезультат умножения: {first_number * second_number}\nРезультат возведения во вторую степень первого числа: {first_number ** 2}\nРезультат возведения во вторую степень второго числа: {second_number ** 2}')

Введите первое число: 3
Введите второе число: 7
Результат сложения: 10
Результат вычитания: -4
Результат умножения: 21
Результат возведения во вторую степень первого числа: 9
Результат возведения во вторую степень второго числа: 49

7. Анкета

In [43]:
# вспомним множественное присваивание в python
# a, b, c = 0, 1, 2
# используйте множественное присваивание,
# чтобы одной строчкой кода запросить у пользователя имя, возраст и профессию
# выведите на экран полученную информацию

name, age, profession = str(input('Ваше имя: ')), str(input('Ваш возраст: ')), str(input('Ваша профессия: '))
print('Имя: ' + name + '\nВозраст: ' + age + '\nПрофессия: ' + profession)

Ваше имя: Катя
Ваш возраст: 22
Ваша профессия: учитель
Имя: Катя
Возраст: 22
Профессия: учитель

8. Поменять местами переменные

In [48]:
# множественное присваивание иногда очень полезно
# запросите у пользователя две любые переменные
# это может быть строка или число, на ваш выбор

# поменяйте их местами одной строчкой кода:
# запишите в первую переменную информацию из второй,
# а во вторую переменную - информацию из первой, используя множественное присваивание

# выведите на экран промежуточные и итоговые результаты

first, second = str(input('Введите первое имя: ')), str(input('Введите второе имя: '))
print('Первое имя: ' + first + ', Второе имя: ' + second)
print('Меняем местами...')
first, second = second, first
print('Первое имя: ' + first + ', Второе имя: ' + second)

Введите первое имя: Таня
Введите второе имя: Саша
Первое имя: Таня, Второе имя: Саша
Меняем местами...
Первое имя: Саша, Второе имя: Таня

9. Дописать функцию

In [52]:
# чаще мы используем множественное присваивание в фунциональном программировании
# например, эта функция считает сумму и произведение двух чисел
# функция принимает на вход (почти как input!) 2 числа
# эти числа запишутся в переменные a и b
def sum_and_product(a, b):
    # напишите здесь код для расчета суммы чисел a и b
    total_sum = a + b
    # а сюда допишите код для подсчета их произведения
    product = a * b
    # функция возвращает результат подсчета - два новых числа
    return total_sum, product

# настало время множественного присваивания
# мы вызывает функцию sum_and_product и передаем ей в качестве аргументов два числа - 5 и 3
# мы помним, что функция возвращает 2 новых числа,
# поэтому результат работы одной функции мы записываем в две переменные: result_sum и result_product
result_sum, result_product = sum_and_product(5, 3)

# выведите на экран result_sum и result_product
print (f'Сумма: {result_sum} \nПроизведение: {result_product}')

Сумма: 8
Произведение: 15

10. Строка и число

In [55]:
# запросите у пользователя 2 числа, используйте str(input())
# сложите два числа, не меняя тип данных, и выведите на экран результат
# преобразуйте числа к виду нужного типа и снова сложите их, выведите результат

# это задание нам уже знакомо:
# попробуйте решить его питонично, используя как можно меньше строк кода
# какие операции можно объединить?
# в каких случаях нам не нужно создавать дополнительные переменные?

first_number, second_number = str(input('Введите число: ')), str(input('Введите еще одно число: '))
print(f'Результат сложения строк: {first_number + second_number} \nРезультат сложения чисел: {int(first_number) + int(second_number)}')

Введите число: 5
Введите еще одно число: 7
Результат сложения строк: 57
Результат сложения чисел: 12